package com.shinowit.dao.mapper;

import com.shinowit.entity.Userinfo;
import com.shinowit.entity.UserinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    int countByExample(UserinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    int deleteByExample(UserinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    List<Userinfo> selectByExample(UserinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    Userinfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    int updateByExampleSelective(@Param("record") Userinfo record, @Param("example") UserinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    int updateByExample(@Param("record") Userinfo record, @Param("example") UserinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    int updateByPrimaryKey(Userinfo record);

    List<Userinfo> selectPage(UserinfoCriteria example);

    Integer selectMaxPrimaryKeyValue();
}