package com.shinowit.entity;

import java.io.Serializable;

public class Stuinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuinfo.stu_id
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuinfo.stu_name
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuinfo.stu_pass
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    private String stuPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stuinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuinfo.stu_id
     *
     * @return the value of stuinfo.stu_id
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuinfo.stu_id
     *
     * @param stuId the value for stuinfo.stu_id
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuinfo.stu_name
     *
     * @return the value of stuinfo.stu_name
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuinfo.stu_name
     *
     * @param stuName the value for stuinfo.stu_name
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuinfo.stu_pass
     *
     * @return the value of stuinfo.stu_pass
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    public String getStuPass() {
        return stuPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuinfo.stu_pass
     *
     * @param stuPass the value for stuinfo.stu_pass
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    public void setStuPass(String stuPass) {
        this.stuPass = stuPass == null ? null : stuPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Stuinfo other = (Stuinfo) that;
        return (this.getStuId() == null ? other.getStuId() == null : this.getStuId().equals(other.getStuId()))
            && (this.getStuName() == null ? other.getStuName() == null : this.getStuName().equals(other.getStuName()))
            && (this.getStuPass() == null ? other.getStuPass() == null : this.getStuPass().equals(other.getStuPass()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuinfo
     *
     * @mbggenerated Tue Dec 23 20:38:10 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStuId() == null) ? 0 : getStuId().hashCode());
        result = prime * result + ((getStuName() == null) ? 0 : getStuName().hashCode());
        result = prime * result + ((getStuPass() == null) ? 0 : getStuPass().hashCode());
        return result;
    }
}